/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import controller.TrainerDashboardController;
import java.awt.Font;
import java.awt.event.KeyEvent;

/**
 *
 * @author Salifa
 */
public class AddTrainer extends javax.swing.JFrame {
    private File selectedFile = null;
    private TrainerDashboardController controller;

    /**
     * Creates new form AddTrainer
     */
    public AddTrainer() {
        initComponents();
        controller = new TrainerDashboardController();
        jName.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 12));
     jName.setText("enter name");

     jNumber.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 12));
     jNumber.setText("enter phone number");

     jAddress.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 12));
     jAddress.setText("enter address");
     
     
     jName.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jNameActionPerformed(evt);
    }
});

jNumber.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jNumberActionPerformed(evt);
    }
});

jAddress.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        jAddressActionPerformed(evt);
    }
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photobtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jAddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jShift = new javax.swing.JComboBox<>();
        jSpeciality = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPhoto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        photobtn.setBackground(new java.awt.Color(4, 39, 56));
        photobtn.setForeground(new java.awt.Color(4, 39, 56));
        photobtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add New Trainer");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");

        jName.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jName.setText("enter name ");
        jName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jName.setVerifyInputWhenFocusTarget(false);
        jName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jNameFocusLost(evt);
            }
        });
        jName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Number:");

        jNumber.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jNumber.setText("enter phone number");
        jNumber.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jNumberFocusLost(evt);
            }
        });
        jNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumberActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("    Address: ");

        jAddress.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jAddress.setText("enter address");
        jAddress.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jAddressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jAddressFocusLost(evt);
            }
        });
        jAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddressActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Shift:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sepeciality:");

        jShift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6AM-10AM", "10AM-3PM", "3PM-8PM", "5pm-10PM" }));
        jShift.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jShiftFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jShiftFocusLost(evt);
            }
        });
        jShift.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jShiftKeyPressed(evt);
            }
        });

        jSpeciality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yoga", "Zumba", "Weight Lifting", "Power Lifting" }));
        jSpeciality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpecialityActionPerformed(evt);
            }
        });
        jSpeciality.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpecialityKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Photo:");

        jPhoto.setText("Chose Photo");
        jPhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPhotoMouseClicked(evt);
            }
        });
        jPhoto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPhotoKeyPressed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout photobtnLayout = new javax.swing.GroupLayout(photobtn);
        photobtn.setLayout(photobtnLayout);
        photobtnLayout.setHorizontalGroup(
            photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photobtnLayout.createSequentialGroup()
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(photobtnLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(photobtnLayout.createSequentialGroup()
                        .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(photobtnLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, photobtnLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNumber, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAddress, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jShift, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpeciality, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPhoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(photobtnLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jButton2)))
                .addGap(121, 171, Short.MAX_VALUE))
        );
        photobtnLayout.setVerticalGroup(
            photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photobtnLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPhoto))
                .addGap(42, 42, 42)
                .addComponent(jButton2)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(photobtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(photobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameActionPerformed
        // TODO add your handling code here:
        jNumber.requestFocusInWindow();
    }//GEN-LAST:event_jNameActionPerformed

    private void jAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddressActionPerformed
        // TODO add your handling code here:
         
          jShift.requestFocusInWindow();
    }//GEN-LAST:event_jAddressActionPerformed

    private void jNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumberActionPerformed
        // TODO add your handling code here:
       
        jAddress.requestFocusInWindow();
    }//GEN-LAST:event_jNumberActionPerformed

    private void jPhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPhotoMouseClicked
 JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "png", "jpeg"));

            int option = fileChooser.showOpenDialog(null);
            if (option == JFileChooser.APPROVE_OPTION) {
             this.selectedFile = fileChooser.getSelectedFile();
                System.out.println("Image path: " + selectedFile.getAbsolutePath());
            }
            // TODO add your handling code here:
    }//GEN-LAST:event_jPhotoMouseClicked

    private void jSpecialityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpecialityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpecialityActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String name = jName.getText();
        String phone = jNumber.getText();
        String address = jAddress.getText();
        String shift = (String) jShift.getSelectedItem();
        String speciality = (String) jSpeciality.getSelectedItem();
        
        if (name.equals("enter name ") || name.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid name", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (phone.equals("enter phone number") || phone.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a valid phone number", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        
        if (address.equals("enter address") || address.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a valid address", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (selectedFile == null) {
            JOptionPane.showMessageDialog(this, "Please select a photo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            FileInputStream fis = new FileInputStream(selectedFile);
            byte[] image = new byte[(int) selectedFile.length()];
            fis.read(image);
            fis.close();
            
            boolean success = controller.addTrainer(name, address, shift, speciality, image,phone);
            
            if (success) {
                JOptionPane.showMessageDialog(this, "Trainer added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                jName.setText("enter name ");
                jAddress.setText("enter address");
                jShift.setSelectedIndex(0);
                jSpeciality.setSelectedIndex(0);
                selectedFile = null;
                
                TrainerDashboardadmin trainerDashboard = new TrainerDashboardadmin();
                trainerDashboard.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add trainer", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading image file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNameFocusGained
        // TODO add your handling code here:
        if (jName.getText().equals("enter name")) {
        jName.setText("");
        jName.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 12));
    }
    }//GEN-LAST:event_jNameFocusGained

    private void jNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNameFocusLost
        // TODO add your handling code here:
        if (jName.getText().trim().isEmpty()) {
        jName.setText("enter name");
        jName.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 12));
    }
    }//GEN-LAST:event_jNameFocusLost

    private void jNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNumberFocusGained
        // TODO add your handling code here:
        if (jNumber.getText().equals("enter phone number")) {
        jNumber.setText("");
        jNumber.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 12));
    }
    }//GEN-LAST:event_jNumberFocusGained

    private void jNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jNumberFocusLost
        // TODO add your handling code here:
        if (jNumber.getText().trim().isEmpty()) {
        jNumber.setText("enter phone number");
        jNumber.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 12));
    }
    }//GEN-LAST:event_jNumberFocusLost

    private void jAddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAddressFocusGained
        // TODO add your handling code here:
        if (jAddress.getText().equals("enter address")) {
        jAddress.setText("");
        jAddress.setFont(new java.awt.Font("Segoe UI", Font.PLAIN, 12));
    }
    }//GEN-LAST:event_jAddressFocusGained

    private void jAddressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jAddressFocusLost
        // TODO add your handling code here:
         if (jAddress.getText().trim().isEmpty()) {
        jAddress.setText("enter address");
        jAddress.setFont(new java.awt.Font("Segoe UI", Font.ITALIC, 12));
    }
    }//GEN-LAST:event_jAddressFocusLost

    private void jShiftFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jShiftFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jShiftFocusGained

    private void jShiftFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jShiftFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jShiftFocusLost

    private void jShiftKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jShiftKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jSpeciality.requestFocusInWindow();
    }
    }//GEN-LAST:event_jShiftKeyPressed

    private void jSpecialityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpecialityKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jButton2.doClick();
    }
    }//GEN-LAST:event_jSpecialityKeyPressed

    private void jPhotoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPhotoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPhotoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTrainer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTrainer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAddress;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jName;
    private javax.swing.JTextField jNumber;
    private javax.swing.JButton jPhoto;
    private javax.swing.JComboBox<String> jShift;
    private javax.swing.JComboBox<String> jSpeciality;
    private javax.swing.JPanel photobtn;
    // End of variables declaration//GEN-END:variables
}
