/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

//import model.CurrentUser;
//import model.UserData;  // You'll need this class
//import dao.WorkoutDAO;
//import controller.WorkoutController;
//import java.sql.Date;
//import java.sql.Connection;
//import javax.swing.JOptionPane;
import model.CurrentUser;
import model.UserData;
import dao.WorkoutDAO;
import controller.WorkoutController;
import java.sql.Date;
import javax.swing.JOptionPane;
import model.WorkoutData;
/**
 *
 * @author Acer
 */
public class AddWorkout extends javax.swing.JFrame {

    /**
     * Creates new form AddWorkout
     */
    public AddWorkout() {
        initComponents();
        // Set current date in YYYY-MM-DD format
//        java.time.LocalDate today = java.time.LocalDate.now();
//        jDate.setText(today.toString());
        
        try {
            // Get current user - this will throw exception if not logged in
            UserData currentUser = CurrentUser.get();
            System.out.println("Current user ID: " + currentUser.getId());
        } catch (IllegalStateException e) {
            // If we get here, it means no user is logged in
            JOptionPane.showMessageDialog(this, "Please log in first");
            this.dispose();
            return;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photobtn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jworkout = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jReps = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        jWeight = new javax.swing.JTextField();
        jSets = new javax.swing.JTextField();
        JDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        photobtn.setBackground(new java.awt.Color(4, 39, 56));
        photobtn.setForeground(new java.awt.Color(4, 39, 56));
        photobtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" AddWorkout");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Workout:");

        jworkout.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jworkout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jworkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jworkoutActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reps:");

        jReps.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jReps.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jReps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRepsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sets:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Weight:");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jWeight.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jWeight.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWeightActionPerformed(evt);
            }
        });

        jSets.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jSets.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jSets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout photobtnLayout = new javax.swing.GroupLayout(photobtn);
        photobtn.setLayout(photobtnLayout);
        photobtnLayout.setHorizontalGroup(
            photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photobtnLayout.createSequentialGroup()
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(photobtnLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(photobtnLayout.createSequentialGroup()
                        .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(photobtnLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, photobtnLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Submit)
                            .addComponent(jworkout, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jReps)
                            .addComponent(jSets)
                            .addComponent(jWeight)
                            .addComponent(JDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        photobtnLayout.setVerticalGroup(
            photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(photobtnLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(JDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jworkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jReps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(photobtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(Submit)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(photobtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(photobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
 
// 
//     
//       try {
//        // 1. Get current user
//        UserData currentUser = CurrentUser.get();
//        
//        // 2. Get and validate date
//        String workoutDate = jDate.getText().trim();
//        if (workoutDate.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Date cannot be empty");
//            return;
//        }
//        
//        // 3. Get and validate workout name
//        String workoutName = jworkout.getText().trim();
//        if (workoutName.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Workout name cannot be empty");
//            return;
//        }
//        
//        // 4. Validate numeric fields
//        int reps, sets, weight;
//        try {
//            reps = Integer.parseInt(jReps.getText().trim());
//            sets = Integer.parseInt(jSets.getText().trim());
//            weight = Integer.parseInt(jWeight.getText().trim());
//            
//            if (reps <= 0 || sets <= 0 || weight <= 0) {
//                JOptionPane.showMessageDialog(this, "Reps, sets and weight must be positive numbers");
//                return;
//            }
//        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this, "Reps, sets and weight must be valid numbers");
//            return;
//        }
//        
//        // 5. Create and add workout using controller
//        WorkoutController controller = new WorkoutController(null);
//        boolean success = controller.addWorkout(
//            currentUser.getId(),
//            workoutDate,
//            workoutName,
//            reps,
//            sets,
//            weight
//        );
//        
//        if (success) {
//            JOptionPane.showMessageDialog(this, "Workout added successfully!");
//            // Clear all fields after successful submission
//            jworkout.setText("");
//            jReps.setText("");
//            jSets.setText("");
//            jWeight.setText("");
//            // Reset date to current date
//            java.time.LocalDate today = java.time.LocalDate.now();
//            jDate.setText(today.toString());
//        } else {
//            JOptionPane.showMessageDialog(this, "Failed to add workout. Please try again.");
//        }
//        
//    } catch (IllegalStateException e) {
//        JOptionPane.showMessageDialog(this, "No user logged in. Please log in first.");
//        this.dispose();
//    } catch (Exception e) {
//        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage());
//        e.printStackTrace();
//    }
 try {
        // 1. Get current user
        UserData currentUser = CurrentUser.get();
        
        // 2. Get and validate date from JDateChooser
        if (JDate.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select a date");
            return;
        }
        
        // Convert Date to SQL Date and then to string in YYYY-MM-DD format
        java.util.Date selectedDate = JDate.getDate();
        String workoutDate = new java.sql.Date(selectedDate.getTime()).toString();
        
        // 3. Get and validate workout name
        String workoutName = jworkout.getText().trim();
        if (workoutName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Workout name cannot be empty");
            return;
        }
        
        // 4. Validate numeric fields
        int reps, sets, weight;
        try {
            reps = Integer.parseInt(jReps.getText().trim());
            sets = Integer.parseInt(jSets.getText().trim());
            weight = Integer.parseInt(jWeight.getText().trim());
            
            if (reps <= 0 || sets <= 0 || weight <= 0) {
                JOptionPane.showMessageDialog(this, "Reps, sets and weight must be positive numbers");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Reps, sets and weight must be valid numbers");
            return;
        }
        
        // 5. Create and add workout using controller
        WorkoutController controller = new WorkoutController(null);
        boolean success = controller.addWorkout(
            currentUser.getId(),
            workoutDate,
            workoutName,
            reps,
            sets,
            weight
        );
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Workout added successfully!");
            // Clear all fields after successful submission
            jworkout.setText("");
            jReps.setText("");
            jSets.setText("");
            jWeight.setText("");
            // Reset date to current date
            JDate.setDate(new java.util.Date());
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add workout. Please try again.");
        }
        
    } catch (IllegalStateException e) {
        JOptionPane.showMessageDialog(this, "No user logged in. Please log in first.");
        this.dispose();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "An unexpected error occurred: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_SubmitActionPerformed

    private void jworkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jworkoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jworkoutActionPerformed
    // GEN-FIRST:event_jTextField2ActionPerformed
    // TODO add your handling code here:
    // GEN-LAST:event_jTextField2ActionPerformed


    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }
    // GEN-FIRST:event_jTextField4ActionPerformed
    // TODO add your handling code here:
    // GEN-LAST:event_jTextField4ActionPerformed
    // GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
//        String date = jDate.getText();
//        String workout = jworkout.getText();
//        String reps = jReps.getText();
//        String sets = jSets.getText();
//        String weight = jWeight.getText();
 if (JDate.getDate() == null) {
        // Handle null date case
        return;
    }
//    String date = new java.sql.Date(JDate.getDate().getTime()).toString();
//    String workout = jworkout.getText();
//    String reps = jReps.getText();
//    String sets = jSets.getText();
//    String weight = jWeight.getText();

    }// GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new AddWorkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDate;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jReps;
    private javax.swing.JTextField jSets;
    private javax.swing.JTextField jWeight;
    private javax.swing.JTextField jworkout;
    private javax.swing.JPanel photobtn;
    // End of variables declaration//GEN-END:variables
}
