/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.*;
import java.io.File;
import controller.LoginController;
import controller.SignUpController;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.SwingUtilities;

/**
 *
 * @author ACER
 */
public class SignUp extends javax.swing.JFrame {
    File selectedFile = null;

    /**
     * Creates new form SignUp
     */

    public SignUp() {
        initComponents();
        setupPlaceholders();
        SwingUtilities.invokeLater(() -> {
            this.getRootPane().requestFocusInWindow();
        });
    }

    private void setupPlaceholders() {
        // --- Name Field ---
        usernameText.setText("Enter your name");
        usernameText.setForeground(Color.GRAY);
        usernameText.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent e) {
                if (usernameText.getText().equals("Enter your name")) {
                    usernameText.setText("");
                    usernameText.setForeground(Color.BLACK);
                }
            }

            public void focusLost(FocusEvent e) {
                if (usernameText.getText().isEmpty()) {
                    usernameText.setText("Enter your name");
                    usernameText.setForeground(Color.GRAY);
                }
            }
        });

        // --- Phone Field ---
        phoneText.setText("Enter phone number");
        phoneText.setForeground(Color.GRAY);
        phoneText.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent e) {
                if (phoneText.getText().equals("Enter phone number")) {
                    phoneText.setText("");
                    phoneText.setForeground(Color.BLACK);
                }
            }

            public void focusLost(FocusEvent e) {
                if (phoneText.getText().isEmpty()) {
                    phoneText.setText("Enter phone number");
                    phoneText.setForeground(Color.GRAY);
                }
            }
        });

        // --- Password Field ---
        passwordText.setEchoChar((char) 0);
        passwordText.setText("Enter your password");
        passwordText.setForeground(Color.GRAY);
        passwordText.addFocusListener(new FocusAdapter() {
            public void focusGained(FocusEvent e) {
                String pwd = new String(passwordText.getPassword());
                if (pwd.equals("Enter your password")) {
                    passwordText.setText("");
                    passwordText.setEchoChar('\u2022');
                    passwordText.setForeground(Color.BLACK);
                }
            }

            public void focusLost(FocusEvent e) {
                String pwd = new String(passwordText.getPassword());
                if (pwd.isEmpty()) {
                    passwordText.setEchoChar((char) 0);
                    passwordText.setText("Enter your password");
                    passwordText.setForeground(Color.GRAY);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        SignUp = new javax.swing.JButton();
        start = new javax.swing.JLabel();
        zenfit = new javax.swing.JLabel();
        journey = new javax.swing.JLabel();
        Fitness = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        phoneText = new javax.swing.JTextField();
        redirectLogin = new javax.swing.JLabel();
        Membership = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        imgBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.orange);
        setForeground(java.awt.Color.gray);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRATION");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(168, 173, 175));
        jLabel2.setText("Enter your details to get started");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 11, Short.MAX_VALUE));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 382, Short.MAX_VALUE));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel4.setText("Password:");

        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });

        passwordText.setVerifyInputWhenFocusTarget(false);
        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });

        SignUp.setText("Signup");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });

        start.setFont(new java.awt.Font("Segoe UI", 1, 52)); // NOI18N
        start.setText("START YOUR");

        zenfit.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        zenfit.setForeground(new java.awt.Color(255, 112, 67));
        zenfit.setText("ZENFIT");

        journey.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        journey.setText("JOURNEY WITH");

        Fitness.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        Fitness.setForeground(new java.awt.Color(255, 112, 67));
        Fitness.setText("FITNESS");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel5.setText("Phone:");

        phoneText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextActionPerformed(evt);
            }
        });

        redirectLogin.setText("Already have an account?");
        redirectLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                redirectLoginMouseClicked(evt);
            }
        });

        Membership.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Membership.setText("Membership:");

        jComboBox1.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Month", "3 Month", "6 Month", "1 Year" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        imgBtn.setText("Choose Image");
        imgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBtnMouseClicked(evt);
            }
        });
        imgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgBtnActionPerformed(evt);
            }
        });
        imgBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                imgBtnKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel7.setText("Picture:");

        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("About us ?");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(115, 115, 115)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(jLabel5)
                                                                                                .addComponent(jLabel3)
                                                                                                .addComponent(jLabel4)
                                                                                                .addComponent(
                                                                                                        Membership)
                                                                                                .addComponent(jLabel7))
                                                                                        .addGap(54, 54, 54)
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                .addComponent(phoneText,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        146,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(
                                                                                                        passwordText,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        146,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGroup(layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                        .addComponent(
                                                                                                                imgBtn,
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                146,
                                                                                                                Short.MAX_VALUE)
                                                                                                        .addComponent(
                                                                                                                jComboBox1,
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                0,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE))))
                                                                                .addComponent(usernameText,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        146,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(258, 258, 258)
                                                                        .addComponent(SignUp,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                105,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(161, 161, 161)
                                                                .addComponent(jLabel6,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 74,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(redirectLogin)))
                                                .addGap(180, 180, 180)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(54, 54, 54)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(start)
                                                                                        .addComponent(journey)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(243, 243, 243)
                                                                                .addComponent(Fitness))))
                                                        .addComponent(zenfit,
                                                                javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(430, 430, 430)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(358, 358, 358)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 520,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(45, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(32, 32, 32)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(usernameText,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                44,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel3))
                                                                .addGap(9, 9, 9)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(phoneText,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                44,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel5))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(passwordText,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                44,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel4))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(jComboBox1)
                                                                        .addComponent(Membership,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(imgBtn,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                35,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel7))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(redirectLogin)
                                                                        .addComponent(jLabel6))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(SignUp,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(start)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Fitness, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(journey, javax.swing.GroupLayout.PREFERRED_SIZE, 74,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(zenfit, javax.swing.GroupLayout.PREFERRED_SIZE, 52,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(145, Short.MAX_VALUE)))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imgBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_imgBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_imgBtnActionPerformed

    private void imgBtnKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_imgBtnKeyPressed
        // TODO add your handling code here:

    }// GEN-LAST:event_imgBtnKeyPressed

    private void imgBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_imgBtnMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser
                .setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Images", "jpg", "png", "jpeg"));

        int option = fileChooser.showOpenDialog(null);
        if (option == JFileChooser.APPROVE_OPTION) {
            this.selectedFile = fileChooser.getSelectedFile();
            System.out.println("Image path: " + selectedFile.getAbsolutePath());
        }
    }// GEN-LAST:event_imgBtnMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:

        try {
            // Get the URL to your index.html resource
            java.net.URL url = getClass().getResource("/index.html");

            if (url != null) {
                Desktop.getDesktop().browse(url.toURI());
            } else {
                JOptionPane.showMessageDialog(this, "About Us page not found!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error opening About Us page", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_jLabel6MouseClicked

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {
        // Move focus to phone field
        phoneText.requestFocusInWindow();
    }

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {
        // Signup button action will be handled by the controller
        SignUp.doClick();
    }

    private void redirectLoginMouseClicked(java.awt.event.MouseEvent evt) {
        // Hide signup window and show login window
        this.setVisible(false);
        Login loginView = new Login();
        LoginController loginController = new LoginController(loginView);
        loginController.open();
        this.dispose(); // Dispose the signup window
    }

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {
        // Signup button action will be handled by the controller
        SignUpController signUpController = new SignUpController(this);
        signUpController.open();
    }

    private void phoneTextActionPerformed(java.awt.event.ActionEvent evt) {
        // Move focus to password field
        passwordText.requestFocusInWindow();
    }

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fitness;
    private javax.swing.JLabel Membership;
    private javax.swing.JButton SignUp;
    private javax.swing.JButton imgBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel journey;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField phoneText;
    private javax.swing.JLabel redirectLogin;
    private javax.swing.JLabel start;
    private javax.swing.JTextField usernameText;
    private javax.swing.JLabel zenfit;
    // End of variables declaration//GEN-END:variables

    // Ensures only one ActionListener is set for the SignUp button
    public void setSignUpListener(ActionListener listener) {
        for (ActionListener al : SignUp.getActionListeners()) {
            SignUp.removeActionListener(al);
        }
        SignUp.addActionListener(listener);
    }

    public javax.swing.JPasswordField getPasswordField() {
        return passwordText;
    }

    public javax.swing.JTextField getUsernameField() {
        return usernameText;
    }

    public String getSelectedMembership() {
        return (String) jComboBox1.getSelectedItem();
    }

    public File getSelectedImageFile() {
        return selectedFile;
    }

    public javax.swing.JTextField getPhone() {
        return phoneText;
    }
}